package com.github.eladrimonos.jasprintellij.services

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.application.WriteAction
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.vfs.LocalFileSystem
import java.io.File
import java.io.StringReader
import java.nio.charset.StandardCharsets
import org.yaml.snakeyaml.Yaml
import org.yaml.snakeyaml.nodes.MappingNode
import org.yaml.snakeyaml.nodes.ScalarNode

/**
 * Injects/updates a delimited, auto-generated set of Melos `scripts` entries that
 * run `jaspr daemon` scoped to a specific package, without touching the rest of the
 * target file (melos.yaml or the root pubspec.yaml `melos:` section) — including any
 * `melos.scripts` entries the user (or Melos itself) already declared there.
 *
 * A single managed block can hold multiple entries — a monorepo commonly has more
 * than one Jaspr package — so [ensureScript] upserts one entry while preserving
 * every other entry already registered in the block.
 */
object MelosScriptInjector {

    private val logger = Logger.getInstance(MelosScriptInjector::class.java)

    const val MARKER_START = "######## auto-generated by Jaspr IntelliJ Plugin, DO NOT MODIFY ########"
    const val MARKER_END = "######## END auto-generated by Jaspr IntelliJ Plugin ########"

    private const val EXEC_COMMAND = "dart pub global run jaspr_cli:jaspr daemon"

    sealed class InjectionResult {
        data class Written(val changed: Boolean) : InjectionResult()
        data class ConflictExistingMelosSection(val message: String) : InjectionResult()
    }

    private data class InsertionPlan(val at: Int, val prefix: String, val baseIndent: String)

    /**
     * Ensures [targetFile] has an up-to-date, delimited `melos.scripts.<scriptName>`
     * entry that runs jaspr daemon filtered to [packageName]. If a `melos:` (and/or
     * `melos.scripts`) section already exists — written by the user, by `melos
     * bootstrap`, or by this plugin — the entry is merged into it in place, leaving
     * every other script untouched. Idempotent: calling it again with the same
     * arguments leaves the file untouched.
     */
    fun ensureScript(targetFile: File, scriptName: String, packageName: String): InjectionResult {
        val originalText = if (targetFile.exists()) targetFile.readText(StandardCharsets.UTF_8) else ""
        val startIdx = indexOfLine(originalText, MARKER_START, from = 0)
        val matchedRange = startIdx?.let { findMatchedBlockRange(originalText, it) }

        val newText = if (matchedRange != null) {
            val indent = blockIndent(originalText, matchedRange.first)
            val merged = parseManagedScripts(originalText, matchedRange, indent) + (scriptName to packageName)
            val block = buildBlock(merged, indent)
            // matchedRange starts at the marker TEXT, not the line — replace from the
            // start of that line too, or the existing indent doubles up with the one
            // `block` already includes.
            val replaceFrom = matchedRange.first - indent.length
            originalText.substring(0, replaceFrom) + block + originalText.substring(matchedRange.last + 1)
        } else {
            val plan = planInsertion(originalText) ?: return InjectionResult.ConflictExistingMelosSection(
                "${targetFile.name} has a top-level 'melos:' section whose structure the Jaspr IntelliJ " +
                    "Plugin doesn't understand (expected a mapping, optionally containing a 'scripts:' " +
                    "mapping). Add the '$scriptName' script to your existing 'melos.scripts' manually."
            )
            val block = buildBlock(mapOf(scriptName to packageName), plan.baseIndent)
            originalText.substring(0, plan.at) + plan.prefix + block + originalText.substring(plan.at)
        }

        return InjectionResult.Written(writeIfChanged(targetFile, newText))
    }

    /** All script names declared under `melos.scripts` in [targetFile] — ours and user-authored alike, sorted. */
    fun listScriptNames(targetFile: File): List<String> {
        if (!targetFile.exists()) return emptyList()
        return try {
            val map = Yaml().load(targetFile.readText(StandardCharsets.UTF_8)) as? Map<*, *> ?: return emptyList()
            val scripts = (map["melos"] as? Map<*, *>)?.get("scripts") as? Map<*, *> ?: return emptyList()
            scripts.keys.filterIsInstance<String>().sorted()
        } catch (e: Exception) {
            logger.warn("Could not list melos script names in ${targetFile.absolutePath}: ${e.message}")
            emptyList()
        }
    }

    /**
     * Figures out where to insert a brand-new managed block when none exists yet,
     * based on the actual structure of [text]:
     * - No top-level `melos:` key → append a fresh `melos:`/`scripts:` section at EOF.
     * - `melos:` exists without a `scripts:` child → add a `scripts:` header right
     *   after it, matching its own child indentation.
     * - `melos.scripts` already exists (foreign or not) → append as additional
     *   siblings, matching the existing entries' indentation.
     * Returns null only when `melos:` (or its `scripts:` child) exists but isn't a
     * mapping — a shape we can't safely edit as text.
     */
    private fun planInsertion(text: String): InsertionPlan? {
        if (text.isBlank()) return InsertionPlan(at = 0, prefix = "melos:\n  scripts:\n", baseIndent = "    ")

        val root = try {
            Yaml().compose(StringReader(text))
        } catch (e: Exception) {
            logger.warn("Could not parse YAML structurally for insertion planning: ${e.message}")
            return null
        } ?: return InsertionPlan(
            at = text.length,
            prefix = if (text.trimEnd('\n').isEmpty()) "melos:\n  scripts:\n" else "\n\nmelos:\n  scripts:\n",
            baseIndent = "    ",
        )

        if (root !is MappingNode) return null

        val melosTuple = root.value.firstOrNull { (it.keyNode as? ScalarNode)?.value == "melos" }
        if (melosTuple == null) {
            val trimmed = text.trimEnd('\n')
            return InsertionPlan(
                at = text.length,
                prefix = if (trimmed.isEmpty()) "melos:\n  scripts:\n" else "\n\nmelos:\n  scripts:\n",
                baseIndent = "    ",
            )
        }
        val melosNode = melosTuple.valueNode as? MappingNode ?: return null

        val scriptsTuple = melosNode.value.firstOrNull { (it.keyNode as? ScalarNode)?.value == "scripts" }
        if (scriptsTuple == null) {
            val melosChildIndent = melosNode.value.firstOrNull()?.keyNode?.startMark?.column
                ?: (melosNode.startMark.column + 2)
            return InsertionPlan(
                at = melosNode.endMark.index,
                prefix = "\n${" ".repeat(melosChildIndent)}scripts:\n",
                baseIndent = " ".repeat(melosChildIndent + 2),
            )
        }

        val scriptsNode = scriptsTuple.valueNode as? MappingNode ?: return null
        val entryIndent = scriptsNode.value.firstOrNull()?.keyNode?.startMark?.column
            ?: (scriptsNode.startMark.column + 2)
        return InsertionPlan(at = scriptsNode.endMark.index, prefix = "\n", baseIndent = " ".repeat(entryIndent))
    }

    private fun buildBlock(scripts: Map<String, String>, baseIndent: String): String = buildString {
        appendLine("$baseIndent$MARKER_START")
        for ((name, packageName) in scripts.toSortedMap()) {
            appendLine("$baseIndent$name:")
            appendLine("${baseIndent}  description: \"Jaspr Daemon using Melos (auto-generated by Jaspr IntelliJ Plugin)\"")
            appendLine("${baseIndent}  exec:")
            appendLine("${baseIndent}    command: $EXEC_COMMAND")
            appendLine("${baseIndent}  packageFilters:")
            appendLine("${baseIndent}    packageName: $packageName")
        }
        append("$baseIndent$MARKER_END")
    }

    /** The exact leading whitespace of the line the managed block's [MARKER_START] sits on. */
    private fun blockIndent(text: String, markerStartIdx: Int): String {
        val lineStart = text.lastIndexOf('\n', markerStartIdx - 1).let { if (it == -1) 0 else it + 1 }
        return text.substring(lineStart, markerStartIdx)
    }

    /** Returns the char range (inclusive) covering both marker lines and everything between them. */
    private fun findMatchedBlockRange(text: String, startIdx: Int): IntRange? {
        val afterStart = startIdx + MARKER_START.length
        val endIdx = indexOfLine(text, MARKER_END, from = afterStart) ?: return null
        val endOfEndLine = endIdx + MARKER_END.length
        return startIdx..(endOfEndLine - 1)
    }

    /** Finds the char offset of a line whose trimmed content exactly equals [marker]. */
    private fun indexOfLine(text: String, marker: String, from: Int): Int? {
        var searchFrom = from
        while (true) {
            val idx = text.indexOf(marker, searchFrom)
            if (idx == -1) return null

            val lineStart = text.lastIndexOf('\n', idx - 1).let { if (it == -1) 0 else it + 1 }
            val lineEndCandidate = text.indexOf('\n', idx).let { if (it == -1) text.length else it }
            if (text.substring(lineStart, lineEndCandidate).trim() == marker) return idx

            searchFrom = idx + marker.length
        }
    }

    /**
     * Parses the `name -> packageName` map already inside the managed block, dedenting
     * by [indent] first so the fragment parses as a plain `name: {...}` mapping.
     * Also understands the legacy (pre-nesting-fix) shape where the whole `melos:
     * scripts:` header lived inside the markers, for back-compat with older blocks.
     */
    private fun parseManagedScripts(text: String, matchedRange: IntRange, indent: String): Map<String, String> {
        val innerStart = matchedRange.first + MARKER_START.length
        val innerEnd = matchedRange.last + 1 - MARKER_END.length
        if (innerEnd <= innerStart) return emptyMap()
        val inner = text.substring(innerStart, innerEnd)
        val dedented = inner.lines().joinToString("\n") { it.removePrefix(indent) }

        return try {
            val map = Yaml().load(dedented) as? Map<*, *> ?: return emptyMap()
            val scriptsMap = (map["melos"] as? Map<*, *>)?.get("scripts") as? Map<*, *> ?: map
            scriptsMap.mapNotNull { (name, value) ->
                val packageName = ((value as? Map<*, *>)?.get("packageFilters") as? Map<*, *>)
                    ?.get("packageName") as? String
                if (name is String && packageName != null) name to packageName else null
            }.toMap()
        } catch (e: Exception) {
            logger.warn("Could not parse existing managed melos scripts: ${e.message}")
            emptyMap()
        }
    }

    /**
     * Writes [newText] to [targetFile] if it differs from the current content, and
     * returns whether anything changed.
     *
     * If the file is already open in an editor (a cached, unmodified [Document]
     * exists for it), the edit goes through that `Document` instead of a raw
     * `java.io` write: editors only repaint from `Document` changes, so writing the
     * bytes directly and refreshing the VFS afterwards leaves an open editor showing
     * stale content until the user switches tabs and back. Writing through the
     * `Document` (and then saving it) updates the editor immediately and keeps disk
     * in sync in the same step.
     */
    private fun writeIfChanged(targetFile: File, newText: String): Boolean {
        val application = ApplicationManager.getApplication()
        if (application != null) {
            val vFile = LocalFileSystem.getInstance().refreshAndFindFileByIoFile(targetFile)
            val fileDocumentManager = FileDocumentManager.getInstance()
            val document = vFile?.let { fileDocumentManager.getCachedDocument(it) }
            if (document != null && !fileDocumentManager.isDocumentUnsaved(document)) {
                if (document.text == newText) return false
                val writeAndSave = Runnable {
                    WriteAction.run<RuntimeException> {
                        document.setText(newText)
                        fileDocumentManager.saveDocument(document)
                    }
                }
                if (application.isDispatchThread) writeAndSave.run() else application.invokeAndWait(writeAndSave)
                return true
            }
        }

        // No open (or no dirty) document to update in place — including when running
        // outside a live IDE instance (e.g. plain unit tests) — fall back to a raw write.
        if (targetFile.exists() && targetFile.readText(StandardCharsets.UTF_8) == newText) return false
        targetFile.parentFile?.mkdirs()
        targetFile.writeText(newText, StandardCharsets.UTF_8)
        if (application != null) {
            LocalFileSystem.getInstance().refreshAndFindFileByIoFile(targetFile)
        }
        return true
    }
}
